version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    command: tail -f /dev/null
  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: database
      POSTGRES_USER: postgres
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

